#! /usr/bin/python

import sys, os, getpass

sys.path = list((os.getcwd() + '/ntlmaps',)) + sys.path
import digest_encrypt

digest_encrypt = digest_encrypt.digest_encrypt()

#password = raw_input("Password to encrypt: ")
password = getpass.getpass('Password to encrypt: ')

KEY='your-key-super-duper-secret-key-here-only-first-32-characters-are-used'
decrypted = digest_encrypt.encrypt(KEY, password)
print 'Encrypted password: ' + decrypted
#print digest_encrypt.decrypt(KEY, decrypted)